CREATE TABLE IF NOT EXISTS vote_content(
vote_content_id INT NOT NULL AUTO_INCREMENT,
vote_id INT NOT NULL,
vote_content_content VARCHAR(300) NOT NULL,
PRIMARY KEY(vote_content_id),
FOREIGN KEY(vote_id) REFERENCES vote_title(vote_id) ON UPDATE CASCADE ON DELETE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;