CREATE TABLE IF NOT EXISTS post_url(
post_id INT NOT NULL,
post_url_link VARCHAR(500) NOT NULL,
post_url_img VARCHAR(500) NULL,
PRIMARY KEY(post_id),
FOREIGN KEY(post_id) REFERENCES post(post_id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;