CREATE TABLE IF NOT EXISTS vote_select(
select_id INT NOT NULL AUTO_INCREMENT,
select_content VARCHAR(100) NOT NULL,
vote_que_id INT NOT NULL,
PRIMARY KEY(select_id),
FOREIGN KEY(vote_que_id) REFERENCES vote_que(vote_que_id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;