CREATE TABLE IF NOT EXISTS user(
user_id VARCHAR(20) NOT NULL,
pw VARCHAR(150) NOT NULL,
user_name VARCHAR(10) NOT NULL,
major_id TINYINT NULL,
nick VARCHAR(30) NOT NULL,
introduce VARCHAR(50) NULL,
PRIMARY KEY (user_id),
FOREIGN KEY (major_id) REFERENCES major(major_id) ON DELETE SET NULL ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;