CREATE TABLE IF NOT EXISTS account_form(
form_id INT NOT NULL AUTO_INCREMENT,
account_id INT NOT NULL,
form VARCHAR(100) NOT NULL,
trader VARCHAR(100) NOT NULL,
item VARCHAR(100) NOT NULL,
price INT NOT NULL DEFAULT 0,
PRIMARY KEY(form_id),
FOREIGN KEY(account_id) REFERENCES account(account_id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;