CREATE TABLE IF NOT EXISTS vote_tag(
vote_id INT NOT NULL,
tag_id SMALLINT NOT NULL,
PRIMARY KEY(vote_id, tag_id),
FOREIGN KEY(vote_id) REFERENCES vote(vote_id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(tag_id) REFERENCES tag(tag_id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;