CREATE TABLE IF NOT EXISTS account(
account_id INT NOT NULL AUTO_INCREMENT,
user_id VARCHAR(20) NULL,
account_title VARCHAR(100) NOT NULL,
account_content VARCHAR(10000) NOT NULL,
account_date DATETIME NOT NULL DEFAULT NOW(),
PRIMARY KEY(account_id),
FOREIGN KEY(user_id) REFERENCES user(user_id) ON DELETE SET NULL ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;