CREATE TABLE IF NOT EXISTS account_tag(
account_id INT NOT NULL,
tag_id SMALLINT NOT NULL,
PRIMARY KEY(account_id, tag_id),
FOREIGN KEY(account_id) REFERENCES account(account_id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY(tag_id) REFERENCES tag(tag_id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;