CREATE TABLE IF NOT EXISTS attachments(
attachment_id INT NOT NULL AUTO_INCREMENT,
post_id INT NOT NULL,
attachment_route VARCHAR(100) NOT NULL,
PRIMARY KEY(attachment_id),
FOREIGN KEY(post_id) REFERENCES post(post_id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;