CREATE TABLE IF NOT EXISTS blacklist(
user_id INT NOT NULL,
deadtime DATETIME NOT NULL,
PRIMARY KEY(user_id),
FOREIGN KEY(user_id) REFERENCES user(user_id) ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;