CREATE TABLE IF NOT EXISTS user_like(
user_id INT NOT NULL,
post_id INT NOT NULL,
PRIMARY KEY(user_id, post_id),
FOREIGN KEY(user_id) REFERENCES user(user_id) ON DELETE CASCADE ON UPDATE CASCADE
FOREIGN KEY(post_id) REFERENCES post(post_id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;