CREATE TABLE IF NOT EXISTS comment(
comment_id INT NOT NULL,
post_id INT NOT NULL,
user_id INT NOT NULL,
comment_content VARCHAR(500) NOT NULL,
PRIMARY KEY(comment_id),
FOREIGN KEY(post_id) REFERENCES post(post_id) ON DELETE CASCADE ON UPDATE CASCADE
FOREIGN KEY(user_id) REFERENCES user(user_id) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;