CREATE TABLE IF NOT EXISTS post(
post_id INT NOT NULL AUTO_INCREMENT,
notice_id INT NOT NULL,
user_id INT NOT NULL,
post_name VARCHAR(100) NULL,
post_content VARCHAR(1500) NOT NULL,
post_view INT NOT NULL, DEFAULT 0,
PRIMARY KEY(post_id),
FOREIGN KEY(notice_id) REFERENCES notice(notice_id) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY(user_id) REFERENCES user(user_id) ON UPDATE CASCADE
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;